name: VoteStreak
main: com.spiny.votestreak.main.VoteStreak
version: 1.5
depends: [Votifier]
commands:
  simvote:
  vote:
    description: Provides detailed information about VoteStreak and its features
    